version: "3.9"

services:
  app:
    environment:
      - MONGODB_URL=mongodb://127.0.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+1.6.0
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app:z
      # O ':z' indica que o volume será compartilhado.
      # Só dever ser necessário se usar o VScode
    command: >
      sh -c "python -m uvicorn src.main:app --host=0.0.0.0 --port=8000 --reload"

